title = 'Dial Maintianer Configs File'

# api服务的配置
[api]
gin_mode = 'release'
host = '127.2'
port = '1111'

# 日志的配置
[log]
level = 'debug'
format = 'text'

[apikey]
prefix = 'runner.'
key = 'AAAA2EAAHBZYcddaSDSxsREs4GdKFrNmWoLMOXwWVnwFv5s7Q8w'
